import { chromium } from 'playwright';
import { pathToFileURL } from 'url';
import path from 'path';
import fs from 'fs';
const root = path.resolve(process.cwd(), '..');
const url = pathToFileURL(path.join(root, 'index.html')).href;
const shots = path.join(process.cwd(), 'shots'); fs.mkdirSync(shots, { recursive: true });
const res = []; const ok = (n, c, x = '') => { res.push([n, !!c, x]); };
const browser = await chromium.launch({ channel: 'msedge', args: ['--use-gl=swiftshader', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1366, height: 768 } });
const errs = [];
page.on('console', m => { const x = m.text(); if ((m.type() === 'error' && !/VALIDATE_STATUS false/.test(x)) || (m.type() === 'warning' && !/GL Driver Message|loseContext|GPU stall/.test(x))) errs.push(m.type() + ': ' + x); });
page.on('pageerror', e => errs.push('pageerror: ' + e.message));
const A0 = (code) => page.evaluate(code);
const t0 = Date.now();
await page.goto(url); await page.waitForFunction(() => window.__ready === true, null, { timeout: 15000 });
ok('loaded < 3s', Date.now() - t0 < 3000, (Date.now() - t0) + 'ms');
const modelOk = await page.waitForFunction(() => window.__app.info().skullSource === 'model', null, { timeout: 25000 }).then(() => true).catch(() => false);
ok('real skull model loaded', modelOk);
ok('overlay visible', await page.isVisible('#startBtn'));
await page.screenshot({ path: shots + '/overlay.png' });
await page.click('#startBtn');
await page.waitForTimeout(600);
ok('overlay hidden', await A0(`document.getElementById('overlay').classList.contains('hide')`));
ok('onboarding shows on first run', await page.isVisible('#coachBubble'));
await page.screenshot({ path: shots + '/onboarding-step1.png' });
await page.click('#coachNext'); await page.waitForTimeout(300); await page.screenshot({ path: shots + '/onboarding-step2.png' });
await page.click('#coachSkip'); await page.waitForTimeout(300);
ok('onboarding stored', await A0(`localStorage.getItem('onboarded')==='1'`));
const parity = await A0(`(function(){var a=Object.keys(App.i18n.es).sort().join(),b=Object.keys(App.i18n.en).sort().join();return a===b})()`);
ok('i18n key parity ES=EN', parity);
await page.screenshot({ path: shots + '/module-intro.png' });
await page.click('#modulesBtn'); await page.waitForTimeout(300); await page.screenshot({ path: shots + '/modules-drawer.png' });
await page.click('#modulesBtn');
await page.click('#settingsBtn'); await page.waitForTimeout(200); await page.screenshot({ path: shots + '/settings.png' }); await page.click('#settingsClose');
const settle = async () => { for (let i = 0; i < 60; i++) { if (!(await page.evaluate('__app.glLost()'))) return; await page.waitForTimeout(250); } };
const snap = async (n) => { await settle(); await page.evaluate('__app.redraw()'); await page.screenshot({ path: shots + '/' + n + '.png' }); };
const A = async (code) => { try { await settle(); } catch (e) {} return page.evaluate(code); };
for (const mode of ['entry', 'exit']) {
  await A(`__app.setMode('${mode}')`);
  for (const tt of [0, 0.3, 0.6, 0.95]) { await A(`__app.setT(${tt})`); await snap(`detail-${mode}-t${Math.round(tt * 100)}`); }
}
for (const id of ['r22', 'p38', 'p45', 'p9', 'r556', 'r762']) {
  await A(`__app.setAmmo('${id}'); __app.setMode('entry'); __app.setT(0.07); __app.camCloseUpBullet()`); await snap('ammo-' + id + '-closeup');
}
await A(`__app.setAmmo('p9'); __app.setHP(true); __app.setMode('exit'); __app.setT(0.45); __app.camCloseUpBullet()`); await snap('hp-exit-t45');
await A(`__app.setHP(false); __app.setAmmo('r556'); __app.setMode('exit'); __app.setT(0.55); __app.camCloseUpBullet()`); await snap('rifle-exit-t55');
await A(`__app.setAmmo('r762'); __app.setCutaway(true); __app.setMode('entry'); __app.setT(0.07); __app.camCloseUpBullet()`); await snap('cutaway-r762');
await A(`__app.setCutaway(false); __app.setAmmo('p9'); __app.setMode('entry'); __app.setView('detail')`);
// ---- phase 4: physics overlays
await A(`__app.setMode('entry'); __app.setT(0.32)`); await snap('forces-entry-t32');
await A(`__app.setT(0.60)`); await snap('forces-entry-t60');
await A(`__app.setOverlay('stress', false); __app.setOverlay('waves', true); __app.setT(0.36)`); await snap('waves-entry-t36');
await A(`__app.setT(0.42)`); await snap('waves-entry-t42');
await A(`__app.setT(0.50)`); await snap('waves-graph-t50');
await A(`__app.setOverlay('waves', false); __app.setOverlay('bend', true); __app.setT(0.45)`); await snap('bend-entry-t45');
await A(`__app.setMode('exit'); __app.setT(0.45)`); await snap('bend-exit-t45');
await A(`__app.setOverlay('bend', false); __app.setOverlay('micro', true); __app.setMode('entry'); __app.setT(0.70)`); await snap('micro-entry-t70');
await A(`__app.setMode('exit'); __app.setT(0.70)`); await snap('micro-exit-t70');
await A(`__app.setOverlay('micro', false); __app.setOverlay('stress', true); __app.setMode('entry')`);
// ---- phase 6: oblique and contact shots
await A(`__app.setView('detail'); __app.setScenario('oblique'); __app.setTheta(35); __app.setMode('entry'); __app.setT(0.95)`); await snap('oblique-entry-t95');
await A(`__app.setMode('exit'); __app.setT(0.95)`); await snap('oblique-exit-t95');
await A(`__app.setTheta(0); __app.setMode('entry'); __app.setT(0.95)`); await snap('oblique-theta0-entry-t95');
await A(`__app.setScenario('contact'); __app.setMode('entry'); __app.setT(0.30)`); await snap('contact-t30');
await A(`__app.setT(0.95)`); await snap('contact-t95');
await A(`__app.setScenario('perp'); __app.setRange('close'); __app.setMode('entry')`);// ---- phase 7: cinematic bullet-time
await A(`__app.setView('detail'); __app.setMode('entry'); __app.setScenario('perp'); __app.setSetting('cinematic', true); __app.setT(0.15)`);
await page.selectOption('#pSpeed', '2'); await A(`__app.play()`);
await page.waitForFunction(() => __app.cineInfo().t > 0.2, null, { timeout: 60000 });
await A(`__app.pause()`); await snap('cinematic-t20');
ok('cinematic camera moved off the normal pose', (await A(`__app.cineInfo().cam[2]`)) < 60, JSON.stringify(await A(`__app.cineInfo().cam`)));
await A(`__app.setT(0.60); __app.play()`);
const fz = await page.waitForFunction(() => __app.cineInfo().freezeLeft > 0, null, { timeout: 90000 }).then(() => true).catch(() => false);
ok('freeze-frame triggers near t=0.70', fz, JSON.stringify(await A(`__app.cineInfo()`)));
await snap('cinematic-freeze');
await A(`__app.pause(); __app.setSetting('cinematic', false)`); await page.selectOption('#pSpeed', '0.5');// ---- hover tooltip + final views
await A(`__app.setView('detail'); __app.setMode('entry'); __app.setT(0.95)`);
await page.mouse.move(430, 356); await page.waitForTimeout(400);
const tipTxt = await A(`(function(){var e=document.getElementById('tip');return e.style.display==='block'?e.textContent:''})()`);
ok('hover tooltip shows the layer', /Diploe/.test(tipTxt), tipTxt.slice(0, 60)); await snap('tooltip-diploe');
await page.mouse.move(5, 700);// ---- closable windows: module card, pause card, popups
await A(`__app.startModule(1)`);
ok('module card shows', await page.isVisible('#modCard'));
await page.keyboard.press('Escape'); await page.waitForTimeout(200);
ok('Esc closes the module card', !(await page.isVisible('#modCard')));
await A(`__app.startModule(2)`); await page.click('#modCard .xbtn'); await page.waitForTimeout(200);
ok('✕ closes the module card', !(await page.isVisible('#modCard')));
await A(`__app.startModule(1)`); await A(`__app.setView('compare')`); await page.waitForTimeout(200);
ok('stale module card disappears on view change', !(await page.isVisible('#modCard')));
await page.click('#settingsBtn'); await page.waitForTimeout(150);
ok('settings opens', await page.isVisible('#settingsModal'));
await page.mouse.click(60, 400); await page.waitForTimeout(150);
ok('click outside closes settings', !(await page.isVisible('#settingsModal')));
await page.click('#modulesBtn'); await page.waitForTimeout(150); await page.keyboard.press('Escape'); await page.waitForTimeout(150);
ok('Esc closes the modules drawer', !(await page.isVisible('#modDrawer')));
await A(`__app.setView('detail'); __app.setScenario('perp')`);// ---- interface modes, share, clicker keys
await page.click('#uiMode button[data-ui="present"]'); await page.waitForTimeout(300);
await A(`__app.setView('detail'); __app.setMode('entry'); __app.setT(0.40)`);
ok('presentation mode on', await A(`document.body.classList.contains('present')`));
ok('presentation caption visible', await page.isVisible('#presCap'));
ok('study panels hidden in presentation', !(await page.isVisible('#why')));
await snap('present-detail-t40');
const st0 = await A(`__app.info().stage`); await page.keyboard.press('PageDown'); await page.waitForTimeout(200);
ok('clicker PageDown goes to the next stage', (await A(`__app.info().stage`)) === st0 + 1);
await page.click('#shareBtn'); await page.waitForTimeout(200);
ok('share modal shows a QR code', await A(`!!document.querySelector('#qrBox svg')`));
await snap('share-qr'); await page.keyboard.press('Escape'); await page.waitForTimeout(150);
await page.click('#uiMode button[data-ui="study"]'); await page.waitForTimeout(300);
ok('back to study mode', !(await A(`document.body.classList.contains('present')`)) && await page.isVisible('#why'));// optional didactic pauses
ok('pauses default OFF', await A(`__app.state.pauses === false`));
await A(`__app.setSetting('pauses', true); __app.setMode('entry'); __app.setT(0.25)`);
await page.selectOption('#pSpeed', '2'); await A(`__app.play()`);
const hitP = await page.evaluate(`__app.runUntilPause(30000)`);
ok('pause triggers at t=0.31', hitP && (await A(`__app.pauseInfo().key`)) === 'pe1', JSON.stringify(await A(`__app.pauseInfo()`)));
await snap('pause-card');
await page.click('#pauseCard button'); await page.waitForTimeout(300);
ok('pause continues', (await A(`__app.pauseInfo()`)) === null);
await A(`__app.setSetting('pauses', false); __app.pause()`); await page.selectOption('#pSpeed', '0.5');
await A(`__app.setView('compare'); __app.setT(0.95)`); await snap('compare-t95');
await A(`__app.setView('skull'); __app.setT(0.95)`); await snap('skull-t95');
await A(`__app.setScenario('tangential'); __app.setView('skull'); __app.setT(0.95)`); await snap('skull-tangential-out');
await A(`__app.skullView('ent_in')`); await snap('skull-tangential-in');
await A(`__app.setScenario('perp'); __app.setView('skull'); __app.setT(0.95)`);
await A(`__app.useFallbackSkull(true)`); await snap('skull-fallback'); ok('fallback skull works', (await A('__app.info().skullSource')) === 'procedural');
await A(`__app.useFallbackSkull(false)`);
await A(`__app.skullView('ent_in')`); await snap('skull-ent-in');
await A(`__app.skullView('ext_out')`); await snap('skull-ext-out');
await A(`__app.skullView('ext_in')`); await snap('skull-ext-in');
await A(`__app.skullView('ent_out')`); await snap('skull-ent-out');
await A(`__app.setMode('entry'); __app.setRange('contact'); __app.setT(0.95)`); await snap('skin-contact');
await A(`__app.setRange('close')`);
await A(`__app.setLang('en'); __app.setMode('entry'); __app.setT(0.95)`); await snap('detail-entry-t95-EN');
await A(`__app.setLang('es')`);
const inf = await A('__app.info()');
console.log(JSON.stringify(inf));
ok('entry inner > outer', inf.holes.entry.inner > inf.holes.entry.outer, JSON.stringify(inf.holes.entry));
ok('exit outer > inner', inf.holes.exit.outer > inf.holes.exit.inner, JSON.stringify(inf.holes.exit));
ok('exit outer > entry inner', inf.holes.exit.outer > inf.holes.entry.inner);
ok('draw calls < 80', inf.calls < 80, inf.calls); ok('tris < 150k', inf.triangles < 150000, inf.triangles);
const t1 = await A(`document.getElementById('roKE') && document.getElementById('roKE').textContent`);
await A(`__app.setAmmo('r762')`); const t2 = await A(`document.getElementById('roKE').textContent`);
ok('KE p9 518', /518/.test(t1), t1); ok('KE 762 2045', /204[45]/.test(t2), t2);
await A(`__app.setAmmo('p9')`);
const title1 = await A(`document.title`); await A(`__app.setLang('en')`); const title2 = await A(`document.title`);
ok('lang switch', title1 !== title2, title1 + ' | ' + title2);
ok('skull angles', inf.angE < 40 && inf.angX < 40, inf.angE.toFixed(0) + '/' + inf.angX.toFixed(0));
await A(`__app.setView('detail'); __app.setT(0.5); __app.pause()`); await page.waitForTimeout(1500);
const r1 = (await A('__app.info()')).renders; await page.waitForTimeout(1500); const r2 = (await A('__app.info()')).renders;
ok('idle renders = 0', r1 === r2, r1 + ' -> ' + r2);
await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(300); await A(`__app.setLang('es'); __app.setView('detail'); __app.setT(0.95)`); await snap('mobile-detail');
ok('mobile layout active', await A(`document.body.classList.contains('mobile')`));
await page.click('#mobNav button[data-sh="why"]'); await page.waitForTimeout(250); ok('mobile sheet opens', await page.isVisible('#why')); await snap('mobile-sheet-why');
await page.click('#mobNav button[data-sh="why"]'); await page.waitForTimeout(150); ok('mobile sheet closes', !(await page.isVisible('#why')));
await A(`__app.setView('skull')`); await snap('mobile-skull'); await A(`__app.setView('detail')`);
await page.setViewportSize({ width: 1366, height: 768 }); await A(`__app.setView('detail'); __app.setT(0.1); __app.play()`); await page.waitForTimeout(3000);
const f = await A('__app.info().fps'); console.log('fps', f); ok('fps >= 2 (software GL; real GPU is far faster)', f >= 2, f);
ok('no console errors', errs.length === 0, errs.slice(0, 5).join(' || '));
console.table(res.map(r => ({ test: r[0], pass: r[1] ? 'PASS' : 'FAIL', info: r[2] })));
await browser.close();
process.exit(res.every(r => r[1]) ? 0 : 1);
